name: OldustCore
main: net.oldust.core.Core
description: A core made for the Oldust server, containing inner plugins that represent server features.
version: 1.0.0
api-version: 1.16
website: https://oldust.net
authors: [ Fadest, Rektb, Ckblck ]
depends: ProtocolLib
softdepend:
  - Conquer